baseURL = "http://erdongheng.com/demo"
#languageCode = "en-us"
title = "My New Hugo Site"
theme = "jeffprod"

[permalinks]
    post = "/:year/:month/:day/:filename"

[taxonomies]
    tag = "tags"
archive = "archives"

